import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/legal-page";
import { BUSINESS_EMAIL, BUSINESS_NAME, POLICY_EFFECTIVE_DATE } from "@/lib/site-config";

export const metadata: Metadata = {
  title: "AI Assistant Disclosure",
  description: `How the ${BUSINESS_NAME} AI-assisted website concierge works, what it can do, and its limitations.`,
  alternates: { canonical: "/ai-disclosure" },
};

const sections = [
  {
    title: "It is an AI assistant, not Cole",
    paragraphs: [
      "The website chat is an automated AI-assisted concierge. It is designed to communicate in a warm, direct style consistent with the business, but it is not Cole, does not speak with human judgment, and should not be treated as a human representative.",
      "The interface and opening notice identify the assistant as AI. It is not intended to deceive visitors or conceal automation.",
    ],
  },
  {
    title: "What it can do",
    bullets: [
      "Answer routine questions about services, general service areas, preparation, and the quote process.",
      "Collect a name, contact method, vehicle, requested service, city, preferred date, and condition notes.",
      "Display a starting estimate generated by fixed server-side pricing rules for supported services.",
      "Create a lead in the private Digital Forge dashboard and alert Cole when human review is needed.",
    ],
  },
  {
    title: "What it cannot do",
    bullets: [
      "Confirm an appointment, guarantee availability, accept a binding contract, or authorize a final price.",
      "Guarantee stain, odor, scratch, oxidation, mold, or defect removal.",
      "Inspect a vehicle as accurately as in-person review or current photos.",
      "Provide legal, medical, financial, insurance, safety, or emergency advice.",
      "Accept Social Security numbers, bank credentials, payment-card details, driver's-license numbers, or other highly sensitive information.",
    ],
  },
  {
    title: "Pricing and human review",
    paragraphs: [
      "The language model is instructed not to invent prices. Starting ranges are calculated separately by business pricing rules. Final pricing depends on the actual vehicle, size, condition, location, requested work, and preparation required.",
      "Heavy pet hair, mold, bodily fluids, severe stains, smoke or urine odor, paint correction, ceramic coating preparation, RV or marine work, fleet work, unusual travel, or uncertain conditions are routed to Cole for review.",
    ],
  },
  {
    title: "Accuracy and reliance",
    paragraphs: [
      "AI output can be incomplete, inaccurate, or misunderstood. Do not rely on a chat response as a final quote, appointment confirmation, warranty, inspection, or promise of a result.",
      "When a response matters to your decision, ask Cole to confirm it. You can always use the direct phone, text, email, or quote form instead of the AI assistant.",
    ],
  },
  {
    title: "Data and privacy",
    paragraphs: [
      <>
        Chat messages may be sent to an AI service provider to generate a response. Recent messages and lead details may be included so the assistant can maintain context. A transcript may be saved with the lead when you request a quote or human follow-up. See the <Link href="/privacy">Privacy Policy</Link> for additional details.
      </>,
      "Do not submit sensitive or confidential information that is unnecessary for a detailing request. By starting the chat, you acknowledge this disclosure and agree to the Privacy Policy and Terms and Conditions.",
    ],
  },
  {
    title: "Safety, misuse, and moderation",
    paragraphs: [
      "The system uses input limits, spam controls, safety screening, and escalation rules. Messages may be refused when they contain harmful, unlawful, abusive, or unrelated content. Repeated misuse may be blocked.",
    ],
  },
  {
    title: "Questions or correction",
    paragraphs: [
      <>
        To correct information provided through the assistant or request human review, contact <a href={`mailto:${BUSINESS_EMAIL}`}>{BUSINESS_EMAIL}</a> or use the direct contact options on the website.
      </>,
    ],
  },
];

export default function AiDisclosurePage() {
  return (
    <LegalPage
      eyebrow="TRANSPARENT AUTOMATION"
      title="AI Assistant Disclosure"
      effectiveDate={POLICY_EFFECTIVE_DATE}
      summary={<>The assistant helps organize a request, but Cole remains responsible for reviewing final pricing, scope, and scheduling.</>}
      sections={sections}
    />
  );
}
