import type { Metadata } from "next";
import { InnerFooter, InnerNav, PageHero } from "@/components/inner-page";
export const metadata: Metadata = { title: "Detailing Services", description: "Interior, full, exterior, paint correction, RV and marine detailing pricing from Cole's Mobile Detailing." };
const groups=[
 {n:"01",title:"Interior Detailing",copy:"A complete reset for the surfaces you touch every day.",prices:[["Sedan","$199"],["Small SUV","$249"],["Van / 3-row SUV","$279"]],items:["Thorough vacuuming","Plastics and vinyl cleaned and dressed","Interior glass cleaned","Seats cleaned and conditioned"]},
 {n:"02",title:"Full Detail",copy:"Interior restoration paired with exterior decontamination and protection.",prices:[["Sedan","$299"],["Small SUV","$349"],["Van / 3-row SUV","$399"]],items:["Complete interior detail","Hand wash","Clay bar and iron decontamination","Wheels and tires","4-month ceramic sealant"]},
 {n:"03",title:"Exterior Detail",copy:"A cleaner, smoother, better-protected finish.",prices:[["Sedan","$175"],["Small SUV","$199"],["Van / 3-row SUV","$220"]],items:["Thorough hand wash","Clay bar","Iron decontamination","Wheel and tire care","4-month ceramic sealant"]},
 {n:"04",title:"Correction + Add-ons",copy:"For paint and interiors that need more than a maintenance detail.",prices:[["Engine bay","+$50"],["1-step enhancement","+$350"],["Paint correction","$500–$950"]],items:["Pet hair: $50+/hour","Stain removal: +$50–100","Final quote based on condition","Mold and excessive contamination quoted separately"]}
];
export default function ServicesPage(){return <main className="inner-page"><InnerNav/><PageHero eyebrow="SERVICE MENU" title="The right process for the finish in front of us." copy="Clear starting prices, owner-level care, and recommendations based on the actual condition of your vehicle." image="/media-v27/images/mercedes-front.webp"/><section className="service-groups">{groups.map(g=><article key={g.n}><div className="service-number">{g.n}</div><div className="service-main"><p>{g.copy}</p><h2>{g.title}</h2><ul>{g.items.map(x=><li key={x}>{x}</li>)}</ul></div><div className="service-prices">{g.prices.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></article>)}</section><section className="service-note"><h2>Condition matters.</h2><p>Prices are starting points and may change for excessive dirt, pet hair, staining, oxidation, mold, or additional labor. Appointments require at least 24 hours of notice.</p><a href="sms:+18126295544">Request a quote by text</a></section><InnerFooter/></main>}
