import type { Metadata } from "next";
import Image from "next/image";
import { InnerFooter, InnerNav, PageHero } from "@/components/inner-page";
export const metadata: Metadata = {
  title: 'Ceramic Coatings',
  description: 'Professional 1-year and 7-year ceramic coating packages in Evansville and Newburgh, Indiana.',
  alternates: { canonical: '/ceramic-coatings' },
  openGraph: { title: 'Ceramic Coatings', description: 'Professional 1-year and 7-year ceramic coating packages in Evansville and Newburgh, Indiana.', url: '/ceramic-coatings' },
};
export default function CeramicPage(){return <main className="inner-page"><InnerNav/><PageHero eyebrow="CERAMIC PROTECTION" title="Gloss that lasts beyond the first wash." copy="Professional paint preparation and coating options for daily drivers, classics, luxury and performance vehicles." image="/media-v27/images/black-camaro.webp"/><section className="coating-page-grid"><article><span>01</span><p>ENTRY PROTECTION</p><h2>1-Year Coating</h2><strong>Starting at $400</strong><ul><li>GYEON Q² CanCoat EVO application</li><li>Hydrophobic behavior</li><li>Enhanced gloss and slickness</li><li>UV and environmental protection</li><li>Easier maintenance washing</li></ul></article><article className="dark"><span>02</span><p>LONG-TERM PROTECTION</p><h2>7-Year Coating</h2><strong>Starting at $1,350</strong><ul><li>Professional-grade durability</li><li>Maximum gloss retention</li><li>Improved chemical resistance</li><li>Long-term paint preservation</li></ul></article></section><section className="coating-process"><div><p>THE PREPARATION</p><h2>A coating can only look as good as the paint beneath it.</h2></div><ol><li><span>01</span>Inspection and consultation</li><li><span>02</span>Safe wash and decontamination</li><li><span>03</span>Paint enhancement or correction</li><li><span>04</span>Panel preparation</li><li><span>05</span>Coating application and curing</li></ol></section><section className="coating-visual"><Image src="/media-v27/images/foam-supercar-front.webp" alt="Corvette covered in foam during preparation" fill sizes="100vw"/></section><section className="coating-care-link"><div><p>AFTERCARE MATTERS</p><h2>Protection performs best when it is maintained correctly.</h2></div><div><p>Review the wash routine, products to avoid, and professional maintenance options designed for coated vehicles.</p><a href="/ceramic-care">View the ceramic care guide</a></div></section><section className="page-cta"><p>PROTECT THE FINISH</p><h2>Request a coating consultation.</h2><a href="sms:+18126295544">Text Cole</a></section><InnerFooter/></main>}
