import type { Metadata } from "next";
import Image from "next/image";
import { InnerFooter, InnerNav, PageHero } from "@/components/inner-page";
export const metadata: Metadata = {
  title: 'About Cole',
  description: "The story behind Cole's Mobile Detailing, an owner-operated Southern Indiana detailing business.",
  alternates: { canonical: '/about' },
  openGraph: { title: 'About Cole', description: "The story behind Cole's Mobile Detailing, an owner-operated Southern Indiana detailing business.", url: '/about' },
};
export default function AboutPage(){return <main className="inner-page"><InnerNav/><PageHero eyebrow="OWNER OPERATED" title="Started in high school. Built with intention." copy="Cole started detailing to earn more, work for himself, and build something he could grow—not just clock into." image="/media-v27/images/porsche-rear.webp"/><section className="about-page-story"><div className="about-page-image"><Image src="/media-v27/images/black-camaro.webp" alt="Classic Camaro detailed by Cole's Mobile Detailing" fill sizes="(max-width:900px) 100vw, 48vw"/></div><div><p className="inner-kicker">THE STORY</p><h2>One business became two.</h2><p>Cole began detailing while still in high school. What started as a way to make extra money became a real business built through repeat customers, word of mouth, and a growing reputation for careful work.</p><p>Today, he studies Business Administration while operating Cole&apos;s Mobile Detailing and Digital Forge, his web design agency. Both businesses are driven by the same idea: presentation matters, details matter, and the work should speak for itself.</p><p>Every appointment is still owner-operated. Customers communicate directly with Cole from the first message through the final inspection.</p><div className="about-values"><span>Owner-operated</span><span>80+ five-star reviews</span><span>Four years in business</span><span>Southern Indiana</span></div></div></section><section className="belief-band"><p>THE STANDARD</p><h2>Daily driver, classic, work truck, or exotic—the process changes. The care does not.</h2></section><section className="page-cta"><p>MEET THE STANDARD</p><h2>Book directly with Cole.</h2><a href="tel:+18126295544">Call 812-629-5544</a></section><InnerFooter/></main>}