import type { Metadata } from "next";
import Image from "next/image";
import { InnerFooter, InnerNav, PageHero } from "@/components/inner-page";
import { stockImages } from "@/lib/stock-images";
export const metadata: Metadata = {
  title: 'Paint Correction',
  description: 'Paint enhancement and multi-stage paint correction in Evansville, Newburgh, and Southern Indiana.',
  alternates: { canonical: '/paint-correction' },
  openGraph: { title: 'Paint Correction', description: 'Paint enhancement and multi-stage paint correction in Evansville, Newburgh, and Southern Indiana.', url: '/paint-correction' },
};
const defects=["Swirl marks from improper washing","Light oxidation and haze","Water-spot etching","Loss of gloss and clarity","Fine scratches and wash marring"];
export default function PaintCorrectionPage(){return <main className="inner-page"><InnerNav/><PageHero eyebrow="PAINT CORRECTION" title="Remove the noise. Reveal the paint." copy="Machine polishing tailored to the condition of your finish—from a gloss-focused enhancement to deeper multi-stage correction." image={stockImages.paintPolishing} imageAlt="Professional paint polishing under inspection lighting" imagePosition="center 52%"/><section className="editorial-split"><div><p className="inner-kicker">THE PURPOSE</p><h2>Correction is not about making paint look different. It is about letting it look like itself again.</h2></div><div><p>Every vehicle is inspected under direct lighting before a recommendation is made. The goal is to improve clarity and reflection without removing more clear coat than necessary.</p><ul>{defects.map(x=><li key={x}>{x}</li>)}</ul></div></section><section className="package-band"><article><span>01</span><p>GLOSS-FOCUSED</p><h2>1-Step Paint Enhancement</h2><strong>Starting at $350</strong><p>Designed to improve gloss and reduce lighter defects on vehicles that do not require aggressive correction.</p></article><article><span>02</span><p>DEEPER RESTORATION</p><h2>Multi-Stage Correction</h2><strong>$500–$950</strong><p>Multiple polishing stages selected for vehicles with heavier swirls, haze, oxidation, and deeper visible defects.</p></article></section><section className="media-proof"><Image src={stockImages.luxuryHero} alt="Deep black luxury paint with crisp reflections" fill sizes="100vw" style={{ objectPosition: "center 60%" }}/><div><p>REFLECTION STUDY</p><h2>Depth is the difference.</h2></div></section><section className="process-rail"><div><p>THE PROCESS</p><h2>Measured. Tested. Refined.</h2></div><ol><li><span>01</span>Wash and decontaminate</li><li><span>02</span>Inspect under controlled lighting</li><li><span>03</span>Test polish and select the process</li><li><span>04</span>Correct and refine the finish</li><li><span>05</span>Protect the restored surface</li></ol></section><section className="page-cta"><p>RESTORE THE REFLECTION</p><h2>Request a paint assessment.</h2><a href="sms:+18126295544">Text Cole</a></section><InnerFooter/></main>}